root: true
env:
    browser: true
    commonjs: true
    node: true
extends:
    - 'eslint:recommended'
    - 'plugin:react/recommended'
    - 'plugin:@typescript-eslint/recommended'
    - 'plugin:react-hooks/recommended'
    - 'plugin:jsx-a11y/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaFeatures:
      jsx: true
    ecmaVersion: 12
    project: './tsconfig.json'
plugins:
    - '@typescript-eslint'
    - 'no-loops'
rules:
    semi: ['error', 'always']
    quotes: ['error', 'single']
    object-curly-spacing: ['error', 'always']
    no-console: 1
    no-multiple-empty-lines: 1
    eol-last: 2
    eqeqeq: 2
    prefer-const: 2
    '@typescript-eslint/no-unused-vars': 1
    react/display-name: 0
    react/no-children-prop: 2
    no-loops/no-loops: 2
    react/react-in-jsx-scope: 0 # No need to import React with NextJS
    jsx-a11y/anchor-is-valid': 0 # This rule is not compatible with Next.js's <Link /> components
    react/prop-types: 0 # Because Typescript is so much better